before_install: 
  - "docker build -t arun696/reactdocker -f dockerfile.dev ."
deploy: 
  access_key_id: $accesskey_id
  app: dockerReact
  bucket_name: elasticbeanstalk-us-east-1-112943594119
  bucket_path: dockerReact
  env: Dockerreact-env
  provider: elasticbeanstalk
  region: us-east-1
  secret_access_key: $acesskey_secret
  true: 
    branch: master
script: 
  - "docker run -e CI=true  arun696/reactdocker npm run test"
services: 
  - docker
sudo: required

